### ISSUE TITLE
Enable support for ELSI

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/siesta-feedstock#30]
Seems like SIESTA could potentially make use of ELSI, since the ELSI library is now available on conda-forge: https://github.com/conda-forge/elsi-feedstock

**Comment by zerothi** [comment]
Yes, however currently we don't have a stable release that has merged the elsi branch. So once that is in, we'll have a look at it. :)

Thanks!

**Comment by zerothi** [comment]
This is now finally something we can do, ELSI, is available in 5.2.0. So we will start looking at this after the coming school...

Thanks!

**Comment by zerothi** [comment]
This is now done for 5.2 (without GPU support).

However, we cannot rely on the `elsi-feedstock` because the subdependency `elpa` is ancient, and does not support newer openmpi versions.

Hence, we rely on elsi through a submodule. Not ideal, but at least we got it!
