### ISSUE TITLE
How can I add postprocessing tools?

### ISSUE THREAD

**Issue by haoasakura12** [conda-forge/siesta-feedstock#36]
### Comment:

Dear,

I installed Siesta 4.1.5 (openmpi version). However, some of the postprocessing tools I need are not in the bin directory, like optical, xv2xsf, among others. 

Is there a way to add these tools after installing the siesta with conda or change the build.sh file before installation?

Thank for your help

**Comment by zerothi** [comment]
You can make a pr and see if it works

**Comment by haoasakura12** [comment]
Sorry... What's a pr?

**Comment by jan-janssen** [comment]
> Is it the Pull Request?

Yes

**Comment by haoasakura12** [comment]
How can I do this?
When I click on "new pull request" it asks me to compare with something...

**Comment by jan-janssen** [comment]
> How can I do this?
> When I click on "new pull request" it asks me to compare with something...

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by haoasakura12** [comment]
Finally, I created the pull request.. I just don't know if it's correct 
Is it right or should I add something more?

**Comment by zerothi** [comment]
Great! Thanks! We'll have a look, but we are approaching vacation times, so response might be a bit long...

**Comment by haoasakura12** [comment]
ok
Thanks

**Comment by zerothi** [comment]
Let us know if the applications will be there as you asked, I think I forgot some of them, but let us know exactly which ones you want! I'll close this.
