### ISSUE TITLE
Support for osx_arm64?

### ISSUE THREAD

**Issue by pfebrer** [conda-forge/siesta-feedstock#51]
### Comment:

Did you try to add the osx_arm64 platform to the compilation? I'm checking the recipe and I see no mention of platforms, but it is only compiled for linux-64 and osx-64, how does that work?

**Comment by jan-janssen** [comment]
I added a request in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5430 still the recipe most likely needs some fine tuning https://conda-forge.org/docs/maintainer/knowledge_base.html#cross-compilation

**Comment by pfebrer** [comment]
Ok, cool! So that repo is what decides which plataforms are attempted?

**Comment by pfebrer** [comment]
Ah ok I read this blog post: https://conda-forge.org/blog/2020/10/29/macos-arm64/

So it seems the required changes should be automatically submitted by a bot in a PR, no?

**Comment by zerothi** [comment]
Done!
