### ISSUE TITLE
Links and default branch

### ISSUE THREAD

**Issue by jme52** [conda-forge/siesta-feedstock#59]
### Comment:

- I believe some of the links (that ultimately appear on the website and the README) could be more appropriate.  I added the changes to https://github.com/jme52/siesta-feedstock/commit/08b190ffde06981a2dfb23cf774e7629cf8e4fbe , but I don't know how to contribute these changes (without triggering a build of the binaries). Can somebody help?
- Would it be possible to change the default branch, or the contents of the main branch? Otherwise users that land on https://github.com/conda-forge/siesta-feedstock will read the README for the last beta release, not for the actual release, that is what we want them to install and use...

**Comment by jme52** [comment]
@zerothi Could you please check this? Thank you!

**Comment by zerothi** [comment]
Yes, I hadn't noticed that the problem arose because I created the branch, I basically shouldn't have created the `v5` branch, instead I should have stayed on `main`.

**Comment by jme52** [comment]
Thanks for fixing the branch issue.

Regarding the links, the old ones are still present on https://github.com/conda-forge/siesta-feedstock/blob/main/README.md and https://anaconda.org/conda-forge/siesta. Am I correct in understanding that the new links from 08b190f will start showing up when you build 5.0.1 later this month?

**Comment by zerothi** [comment]
yes!
